name: flutter_applepay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-180.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^10.1.1
  http: ^1.2.1
  pay: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
